version: '3.8'

services:
  volleyball_tracker:
    build: .
    container_name: volleyball_tracker
    restart: unless-stopped
    volumes:
      - ./media:/app/media
      - ./data:/app/data
      - ./staticfiles:/app/staticfiles
    environment:
      - DJANGO_DEBUG=False

  nginx:
    image: nginx:alpine
    container_name: volley_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - volleyball_tracker