version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: volley_redis
    restart: unless-stopped

  volleyball_tracker:
    build: .
    container_name: volleyball_tracker
    restart: unless-stopped
    volumes:
      - ${MEDIA_PATH:-./media}:/app/media
      - ./data:/app/data
      - ./staticfiles:/app/staticfiles
    environment:
      - DJANGO_DEBUG=False
    depends_on:
      - redis

  celery:
    build: .
    container_name: volley_celery
    restart: unless-stopped
    command: celery -A MyVolleyApp worker --loglevel=info
    volumes:
      - ${MEDIA_PATH:-./media}:/app/media
      - ./data:/app/data
    environment:
      - DJANGO_DEBUG=False
    depends_on:
      - redis
      - volleyball_tracker

  nginx:
    image: nginx:alpine
    container_name: volley_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ${MEDIA_PATH:-./media}:/app/media
      - ./staticfiles:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - volleyball_tracker