# Generated by Django 6.0.3 on 2026-03-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
