# Generated by Django 6.0.3 on 2026-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('processing', 'В очереди / Обрабатывается'), ('ready', 'Готово'), ('error', 'Ошибка')], default='processing', max_length=20),
        ),
    ]
